import {
  Output,
  OnInit,
  AfterContentInit,
  OnChanges,
  Component,
  ElementRef,
  forwardRef
} from '@angular/core';
import { base } from './base';
export class pivottreemapMetaData {
  public static XTYPE: string = 'pivottreemap';
  public static PROPERTIESOBJECT: any = {
    "ariaAttributes": "Object",
    "ariaDescribedBy": "String",
    "ariaLabel": "String",
    "ariaLabelledBy": "String",
    "autoExpand": "Boolean",
    "bind": "Object/String",
    "border": "Boolean",
    "busyLayoutText": "String",
    "clipScene": "Boolean",
    "cls": "String/String[]",
    "colorAxis": "Ext.d3.axis.Color",
    "componentCls": "String",
    "controller": "String/Object/Ext.app.ViewController",
    "defaultListenerScope": "Boolean",
    "disabled": "Boolean",
    "eventHandlers": "Object",
    "expandEventName": "String/String[]",
    "focusCls": "String",
    "height": "Number/String",
    "hidden": "Boolean",
    "hideMode": "'clip'/'display'/'offsets'/'opacity'/'visibility'",
    "hierarchyCls": "String",
    "instanceCls": "String/String[]",
    "interactions": "any",
    "keyMap": "Object",
    "keyMapEnabled": "Boolean",
    "keyMapTarget": "String",
    "layout": "Function",
    "leafTile": "Object",
    "linkKey": "Function",
    "listeners": "Object",
    "matrix": "Ext.pivot.matrix.Base",
    "name": "String",
    "nameable": "Boolean",
    "nodeChildren": "Function",
    "nodeClass": "Function",
    "nodeKey": "Function",
    "nodeText": "Function/String/String[]",
    "nodeTransform": "Function",
    "nodeValue": "Function/String/Number",
    "noParentValue": "Boolean",
    "noSizeLayout": "Boolean",
    "padding": "Object/String/Number",
    "parentTile": "Object",
    "plugins": "Array/Ext.enums.Plugin/Object/Ext.plugin.Abstract",
    "publishes": "String/String[]/Object",
    "reference": "String",
    "renderLinks": "Boolean",
    "renderTo": "Ext.Element",
    "ripple": "Boolean/Object/String",
    "rootVisible": "Boolean",
    "scaleLabels": "Boolean",
    "selectEventName": "String/String[]",
    "selection": "Ext.data.TreeModel",
    "session": "Boolean/Object/Ext.data.Session",
    "shareableName": "Boolean",
    "size": "Object",
    "sorter": "Function",
    "store": "Ext.data.Store",
    "style": "String/Object",
    "tiling": "Function",
    "tooltip": "Ext.tip.ToolTip",
    "touchAction": "Object",
    "transitions": "any",
    "twoWayBindable": "String/String[]/Object",
    "ui": "String/String[]",
    "userCls": "String/String[]",
    "viewModel": "String/Object/Ext.app.ViewModel",
    "width": "Number/String",
    "platformConfig": "Object",
    "responsiveConfig": "Object",
    "fitToParent": "Boolean",
    "config": "Object",
};
  public static PROPERTIES: string[] = [
    'ariaAttributes',
    'ariaDescribedBy',
    'ariaLabel',
    'ariaLabelledBy',
    'autoExpand',
    'bind',
    'border',
    'busyLayoutText',
    'clipScene',
    'cls',
    'colorAxis',
    'componentCls',
    'controller',
    'defaultListenerScope',
    'disabled',
    'eventHandlers',
    'expandEventName',
    'focusCls',
    'height',
    'hidden',
    'hideMode',
    'hierarchyCls',
    'instanceCls',
    'interactions',
    'keyMap',
    'keyMapEnabled',
    'keyMapTarget',
    'layout',
    'leafTile',
    'linkKey',
    'listeners',
    'matrix',
    'name',
    'nameable',
    'nodeChildren',
    'nodeClass',
    'nodeKey',
    'nodeText',
    'nodeTransform',
    'nodeValue',
    'noParentValue',
    'noSizeLayout',
    'padding',
    'parentTile',
    'plugins',
    'publishes',
    'reference',
    'renderLinks',
    'renderTo',
    'ripple',
    'rootVisible',
    'scaleLabels',
    'selectEventName',
    'selection',
    'session',
    'shareableName',
    'size',
    'sorter',
    'store',
    'style',
    'tiling',
    'tooltip',
    'touchAction',
    'transitions',
    'twoWayBindable',
    'ui',
    'userCls',
    'viewModel',
    'width',
    'platformConfig',
    'responsiveConfig',
    'fitToParent',
    'config'
];
  public static EVENTS: any[] = [
		{name:'beforedisabledchange',parameters:'sender,value,oldValue,undefined'},
		{name:'beforeheightchange',parameters:'sender,value,oldValue,undefined'},
		{name:'beforehiddenchange',parameters:'sender,value,oldValue,undefined'},
		{name:'beforewidthchange',parameters:'sender,value,oldValue,undefined'},
		{name:'blur',parameters:'pivottreemap,event'},
		{name:'disabledchange',parameters:'sender,value,oldValue'},
		{name:'focus',parameters:'pivottreemap,event'},
		{name:'focusenter',parameters:'pivottreemap,event'},
		{name:'focusleave',parameters:'pivottreemap,event'},
		{name:'heightchange',parameters:'sender,value,oldValue'},
		{name:'hiddenchange',parameters:'sender,value,oldValue'},
		{name:'layout',parameters:'component'},
		{name:'sceneresize',parameters:'component,scene,size'},
		{name:'scenesetup',parameters:'component,scene'},
		{name:'widthchange',parameters:'sender,value,oldValue'},
		{name:'ready',parameters:''}
];
  public static EVENTNAMES: string[] = [
		'beforedisabledchange',
		'beforeheightchange',
		'beforehiddenchange',
		'beforewidthchange',
		'blur',
		'disabledchange',
		'focus',
		'focusenter',
		'focusleave',
		'heightchange',
		'hiddenchange',
		'layout',
		'sceneresize',
		'scenesetup',
		'widthchange',
		'ready'
];
}
@Component({
  selector: 'pivottreemap', 
  inputs: pivottreemapMetaData.PROPERTIES,
  outputs: pivottreemapMetaData.EVENTNAMES,
  providers: [{provide: base, useExisting: forwardRef(() => ExtPivottreemapComponent)}],
  template: '<ng-template #dynamic></ng-template>'
})
export class ExtPivottreemapComponent extends base implements OnInit,AfterContentInit,OnChanges {
  constructor(eRef:ElementRef) {super(eRef,pivottreemapMetaData)}
  public ngOnInit() {this.baseOnInit(pivottreemapMetaData)}
  //public ngOnChanges(changes: SimpleChanges) {this.baseOnChanges(changes)}
  public ngAfterContentInit() {
    this.baseAfterContentInit()
    this['ready'].emit(this)
    }
}